#!/usr/bin/perl
use locale;
use POSIX qw(locale_h);
require 5.004;
setlocale(LC_ALL, "eo");

undef $/;  #legu per while(<>) la tutan dosieron.

#komencaj aĵoj
print "\\documentclass{article}\n" 
    ."\\usepackage[a5paper]{geometry}\n" # per tio ĉi eble fari a5libreton, sed bedaŭrinde ne eblas per mia printilo (ankaŭ ŝanĝu en makedvi)
#    ."\\usepackage[a4paper, twoside]{geometry}\n"
    ."\\usepackage[esperanto]{babel}\n"
    ."\\usepackage{dotlessj}\n"
   ."\\usepackage{charter}\n"
#   ."\\usepackage{bookman}\n"
#    ."\\usepackage{utopia}\n"
#    ."\\usepackage{newcent}\n"
#    ."\\usepackage{palatcm}\n"
    ."\\usepackage{sectsty}\n"
    ."\\allsectionsfont{\\centering}\n"
#    ."\\def\\jx{j\\hspace{-0.6ex}\\^{ }}\n"
    ."\\def\\jx{\\^\\j }\n"
    ."\\def\\rim#1{}  % `rimarko'\n"
    ."\\def\\a#1{\n\n"
    ."  {\\normalsize\n"
    ."    \\hspace*{-5em}\\vspace*{-2.5ex}\n"
    ."    {\\tiny \\parbox{5em}{\\raggedleft\\noindent #1}}\n"
    ."    }\n\n"
    ."    }\n\n"
    ."\\def\\ax#1{\\a{#1}\\noindent}\n";
while (<>) {    
    s|ŝtrumpetojn|ŝtrump\\-et\\-ojn|g;
    s|antaŭnelonge|antaŭ\\-ne\\-longe|g;
    s|eksport|eks\\-port|g;
    s|renkont|ren\\-kont|g;
    s|rezignaciad|re\\-zig\\-naci\\-ad|g;
    s|promenbaston|pro\\-men\\-bas\\-ton|g;   
    s|akvoamaso|akvo\\-amaso|g;   
    s|salajro|sa\\-laj\\-ro|g;   
    s|rapidtrajno|ra\\-pid\\-trajno|g;   
    s|ĉirkaŭrigardis|ĉirkaŭ\\-ri\\-gar\\-dis|g;
#    s|([iao])s\b|\\-$1s|g;
#    s|(\w{3,})([oa][jn]{1,2})\b|$1\\-$2|g;    
    s|ĉ|\\^c|g;
    s|Ĉ|\\^C|g;
    s|ĝ|\\^g|g;
    s|Ĝ|\\^G|g;
    s|ĥ|\\^h|g;
    s|Ĥ|\\^H|g;
    s|ĵ|\\jx |g;
#    s|ĵ|\\^{\\j}|g;
#    s|ĵ|\\^{j}|g;
    s|Ĵ|\\^J|g;
    s|ŝ|\\^s|g;
    s|Ŝ|\\^S|g;
    s|ŭ|\\u{u}|g;
    s|Ŭ|\\u{U}|g;
    s|versio:(.*)|\\date{$1}|ig;
    s|mHeader\("(.*?)".*?\);|?> \\title{$1} <?php |i;
    s|<!--TITOLPAGXO-->|\\begin{document}\n\\input{titolpag.tex}\n|g;
    s|</?p>|\n\n|g;
    s|<\?php mmNumber\('(.*?\.1)'\) \?>|\\ax{$1}|g;
    s|<\?php mmNumber\('(.*?)'\) \?>|\\a{$1}|g;
    s|<\?php mmChapter\('(.*?)'\) \?>|\\section*{$1}|g;
    s|<\?php.*?\?>| |sg;
#    s|<!-- -->(.*) <!-- -->||g;
    s|<em>(.*)</em>|{\\em $1 }|g;
    s|<!--NELATEX-->.*?<!--/NELATEX-->| |sg;
    s|<!--FINO-->|\n\n\\vspace{2ex}\\noindent|g;
    s|\n?<!--.*?-->\n?| |sg;  # ? zorgas ke la plej malgranda parto trafigxu, s ke ankaux \n estu en .
 

    s|<a href=\"\#.*?\*</a>||g;
    s|<hr />|\n\n\\vspace{2ex}\\noindent|g;
    s|&(.)grave;|\\`$1|g;
    s|&(.)acute;|\\'$1|g;
    s/&(.)uml;/\\"$1/g;
    s|<[^>]*?>||gs;
    s|[ ]+| |g;
    s|\n{2,}|\n\n|g;
    print;
};

print "\\end{document}";
# Local variables:
# coding: utf-8
# End:
